import React, { useMemo } from 'react';
import { Droplet, Leaf, Globe, Shield, RefreshCw } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';
import { useMockState } from '../../context/MockStateContext';
import { SustainabilityCard, ProgressRing } from '../../components/ui/innovation/InnovationComponents';
import ChartCard from '../../components/ui/cards/ChartCard';

export default function Sustainability() {
  const { assets } = useMockState();

  // Compute ESG metrics
  const esgStats = useMemo(() => {
    // Total carbon offsets (KG of CO2) simulated
    const repairedCount = assets.filter(a => a.condition === 'Fair' || a.condition === 'Good').length;
    const carbonSaved = repairedCount * 45; // simulated 45 kg saved per repaired device

    const averageESG = 84;

    return {
      carbonSaved,
      averageESG,
      scanned: assets.length
    };
  }, [assets]);

  // Carbon saves over weeks
  const carbonHistory = [
    { week: 'W1', CarbonOffset: 120 },
    { week: 'W2', CarbonOffset: 185 },
    { week: 'W3', CarbonOffset: 240 },
    { week: 'W4', CarbonOffset: esgStats.carbonSaved }
  ];

  return (
    <div className="flex flex-col gap-6 select-none">
      {/* Header */}
      <div>
        <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
          <Droplet className="w-5.5 h-5.5 text-brand-success animate-pulse" />
          <span>ESG Sustainability Dashboard</span>
        </h2>
        <p className="text-xs text-brand-secondaryText mt-1">Monitor the ecological footprint of hardware lifecycles, carbon offset scores, and repair recycling indexes.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Core sustainability score */}
        <div className="glass-panel p-6 rounded-2xl border border-brand-border/40 bg-[#111827] flex flex-col items-center justify-center text-center gap-4 self-start">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Corporate Green Score</h3>
          
          <ProgressRing value={esgStats.averageESG} size={110} strokeWidth={9} label="ESG Index" />
          
          <div className="space-y-1">
            <span className="text-sm font-bold text-white block">Environmental Index Rating</span>
            <p className="text-xs text-brand-secondaryText px-4 leading-relaxed">
              Calculates corporate hardware lifecycle efficiency, repair vs replace percentages, and shipping overhead footprint.
            </p>
          </div>

          <div className="w-full grid grid-cols-2 gap-2.5 border-t border-brand-border/20 pt-4 font-mono text-xs text-brand-secondaryText">
            <div>
              <span className="text-[9px] text-slate-500 block uppercase font-bold">Carbon Offset</span>
              <span className="text-brand-success font-bold">{esgStats.carbonSaved} kg CO₂</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-500 block uppercase font-bold">Standard Grade</span>
              <span className="text-white font-bold">A- Prime</span>
            </div>
          </div>
        </div>

        {/* Carbon offsets curve */}
        <div className="lg:col-span-2">
          <ChartCard
            title="Carbon Offsets Curve history"
            subtitle="Diagnostic metric mapping corporate carbon offsets generated by hardware checkoffs."
          >
            <div className="h-[200px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={carbonHistory} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                  <defs>
                    <linearGradient id="greenColor" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#22C55E" stopOpacity={0.25} />
                      <stop offset="95%" stopColor="#22C55E" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.02)" />
                  <XAxis dataKey="week" stroke="#64748B" fontSize={10} tickLine={false} />
                  <YAxis stroke="#64748B" fontSize={10} tickLine={false} />
                  <Tooltip
                    contentStyle={{
                      background: '#060816',
                      border: '1px solid rgba(255,255,255,0.05)',
                      borderRadius: '12px',
                      fontSize: '11px',
                      color: '#fff'
                    }}
                  />
                  <Area type="monotone" dataKey="CarbonOffset" stroke="#22C55E" strokeWidth={2.5} fillOpacity={1} fill="url(#greenColor)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </ChartCard>
        </div>
      </div>

      {/* ESG breakdown cards */}
      <div className="flex flex-col gap-4">
        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Environmental Performance Ledgers</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          <SustainabilityCard
            title="Developer Workstations Pool"
            value={88}
            carbonSaved={280}
            repairRatio="4:1 Ratio"
            grade="A"
          />
          <SustainabilityCard
            title="Locker Storage Reserves"
            value={76}
            carbonSaved={140}
            repairRatio="2:1 Ratio"
            grade="B+"
          />
          <SustainabilityCard
            title="Core Networking Racks"
            value={92}
            carbonSaved={esgStats.carbonSaved - 420}
            repairRatio="6:1 Ratio"
            grade="A+"
          />
        </div>
      </div>
    </div>
  );
}
